### ISSUE TITLE
файл создания окна

### ISSUE THREAD

**Issue by javinchi-iOS** [vectozavr/shooter#10]
привет, я тут решил покапаться в коде и поиграться с игрой, и хочу сделать спавны игрков и тд, я захотел испытать в этом проэкте имгуй, в итоге не могу найти файл с созданием окна (sf::RenderWindow) и прочей штукенцией, помоги пожалуйста, где находиться файл с этим созданием, весь проект перерыл и не нашел :(

**Comment by DamirLut** [comment]
Engine > io > Screen.cpp

**Comment by javinchi-iOS** [comment]
там нету sf::RenderWindow

**Comment by vectozavr** [comment]
Всё, что связано с открытием и использованием окна находится в Screen.cpp
Указатель на экземпляр sf::RenderWindow создаётся в Screen.h
