### ISSUE TITLE
Как сбилдить игру?

### ISSUE THREAD

**Issue by MegaOmegaSanSUS** [vectozavr/shooter#17]
Либо я тупой (скорее всего это), либо я тупой (тоже возможно). Но я не могу сбилдить игру. Как это сделать?

**Comment by HyperCodi** [comment]
У меня тоже такой вопрос.

**Comment by HyperCodi** [comment]
Я знаю как это всё сбилдить.

**Comment by vectozavr** [comment]
Инструкция по установке компилятора MinGW и рабочей среды Clion [находится в здесь](https://vectozavr.ru/lesson.php?id_article=0)
Также там есть основы языка C++.

**Comment by HyperCodi** [comment]
Нужен CLion.Открываешь CMakeLists.txt как проект.В CMakeLists.txt на 118 строке делаешь путь к SFML.

**Comment by HyperCodi** [comment]
Добавляешь в путь lib/cmake/sfml.И делаешь конфигурацию.

**Comment by HyperCodi** [comment]
![Безымянный](https://user-images.githubusercontent.com/113190512/189529413-c1e74429-0d8b-41c7-8c11-ee7efbb148c6.png)
