### ISSUE TITLE
Где находиться часть кода где дробовику добавляется отдача?

### ISSUE THREAD

**Issue by Ivan228-s** [vectozavr/shooter#18]
Я пишу читы на игру, но не могу найти часть с дробовиком :(

**Comment by vectozavr** [comment]
It is inside [PlayerController.cpp](https://github.com/vectozavr/shooter/blob/1dccac0085a437f7a00e4e7b8c6faf8d65c19aa0/player/PlayerController.cpp#LL161C3-L169C6) class.
