### ISSUE TITLE
Синий экран смерти после нажатия кнопки "i"

### ISSUE THREAD

**Issue by AnikeyPS** [vectozavr/shooter#21]
После того, как я начал компилировать код (исходный) сначала возникла 1 проблема - не видит функции popen, ну пошел лазить по сайтам. Нашел типо _popen и popen одинаковы. Так она запустилась, но проблемы остались. Зашел в игру и начал изучать клавиши нажатием. После мелкого тыканья мне вылетел BSoD о видео драйвере. Он полетел, после того как я нажал кнопку "I". Тогда моя ОС просто подвисла ии... все - BSoD. Не знаю с чем это связано, но дальше играть я не намерен. У меня Windows

**Comment by vectozavr** [comment]
Thank you for your report – we will work to handle this questions.
