### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by Xhayla** [vectozavr/shooter#5]
![err](https://user-images.githubusercontent.com/54450995/180133486-b4220277-d64b-4ced-88b6-eb85d404b3ab.PNG)

**Comment by Xhayla** [comment]
Что делать?)

**Comment by vectozavr** [comment]
Ошибка 0xc000007b означает, что не хватает каких-то библиотек. Попробуйте поставить OpenAL: https://openal.org/downloads/

**Comment by Xhayla** [comment]
Еще такой вопрос, как открыть игру или сервер в VS, обязательно ли иметь CLion? Просто у меня не получается скомпилировать.

**Comment by Xhayla** [comment]
Я собрал и даже запустил игру через CLion, но как открыть проект в VisualStudio? shooter.sln файла нет.

**Comment by vectozavr** [comment]
Да, я отказался от идеи поддерживать .sln файлы для VS: слишком много уходит время на их поддержание. Не обязательно работать в VS: можно просто собирать проект с помощью CMake напрямую (https://vectozavr.ru/lesson.php?id_article=0)
